config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  #devise_for :admins, :skip => [:sessions]
  #as :admin do
  #  get 'signin' => 'devise/sessions#new', :as => :new_admin_session
  #  post 'signin' => 'devise/sessions#create', :as => :admin_session
  #  delete 'signout' => 'devise/sessions#destroy', :as => :destroy_admin_session
  #end
  #root to: "users#index"
  root to: "home#index"
  #root "application#index"

  get 'home/index'
  #devise_for :users
  
  resources :microposts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    validates :content, length: { maximum: 140 }, presence: true
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
   #      :recoverable, :rememberable, :validatable
    has_many :microposts
    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    private
   
    def configure_permitted_parameters
      #devise_parameter_sanitizer.for(:sign_up) << :username
      devise_parameter_sanitizer.permit(:sign_up, keys: [:adminname])
    end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  #before_action :set_micropost, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, :only => [:create
  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: "Micropost was successfully created." }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Micropost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: %i[ show edit update destroy ]
    before_action :authenticate_admin!, :only => [:new, :create]
  # GET /users or /users.json
  def index
    @users = User.all
  end

   # GET /users/1 or /users/1.json
   def show
    @user = User.find(params[:id])
   # @user = current_user
   end

   # GET /users/new
  def new
   # @user = User.new
  end

    # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.author = current_admin.adminname
    
    if @user.save
      redirect_to @user
    else
      render action: 'new'
    end
  end


  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render action: 'edit'
    end    
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to user_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<%#h3> Application#index </h3%>
<%#p>Find me in app/views/application/index.html.erb</p%>

app/views/home/index.html.erb
<!--h1>Home#index</h1-->
<!--p>Find me in app/views/home/index.html.erb</p-->

app/views/layouts/appl.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <script src="/assets/application.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link data-require="bootstrap@*" data-semver="3.2.0" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.css" />
    <script data-require="bootstrap@*" data-semver="3.2.0" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>      
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "Blog & RoR", home_index_path, class: "navbar-brand" %>
              <% if user_signed_in? %>
                <% welcome_username = 'Hi, ' + current_user.username + '!' %>
                <div class="visible-xs-block" style="margin: 15px 75px" align="right">
                  <%= welcome_username %>
                </div>
              <% end %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><%= link_to "Articles", articles_path, class: "active" %></li>
                <li><%= link_to "New", new_article_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% unless user_signed_in? %>
                  <li><%= link_to "Sign In", new_user_session_path %></li>
                  <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <% else %>
                  <li><div class="hidden-xs" style="margin-top: 15px"><%= welcome_username %></div></li>
                  <li><%= link_to "Sing Out", destroy_user_session_path, method: :delete %></li>
                <% end %>
              </ul>
            </div><!-- /.navbar-collapse -->
      </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <script src="/assets/application.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link data-require="bootstrap@*" data-semver="3.2.0" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.2.0/dist/css/bootstrap.min.css/%>
        <script data-require="bootstrap@*" data-semver="3.2.0" src="https://cdn.jsdelivr.net/npm/bootstrap@3.2.0/dist/js/bootstrap.min.js"></script>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>      
  </head>

  <body>
     <div class="container">
       <nav class="navbar navbar-default" role="navigation">
         <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "ToyApp", home_index_path, class: "navbar-brand" %>
              <% if admin_signed_in? %>
                <% welcome_adminname = 'Hi, ' + current_admin.adminname.to_s + '!' %> 
                              <div class="visible-xs-block" style="margin: 15px 75px" align="right">
                  <%= welcome_adminname %>
                </div>
              <% end %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><%= link_to "Admins", admin_session_path, class: "active" %></li>
                <li><%= link_to "Users", users_path, class: "active" %></li>
                <li><%= link_to "New", new_admin_session_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% unless admin_signed_in? %>
                  <li><%= link_to "Sign In", new_admin_session_path %></li>
                  <li><%= link_to "Sign Up", new_admin_registration_path %></li>
                <% else %>
                  <li><div class="hidden-xs" style="margin-top: 15px"><%= welcome_adminname %></div></li>
                  <li><%= link_to "Sing Out", destroy_admin_session_path, method: :delete %></li>
                <% end %>
              </ul>
            </div><!-- /.navbar-collapse -->
      </nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/shoe.erb
<h3><%= @article.title %></h3>
<p>
	<%= @article.text %>
	<br />
	<br />
	<i>Create <%= @article.author %> at <%= @article.created_at %></i>
	<hr/>
</p>

<h4>Comments</h4>

<% @article.comments.each do |comment| %>

	<p>
		<%= comment.body %>
		<br />
		<br />
		<i>Said <%= comment.author %> at <%= comment.created_at %></i>
		<hr/>
	</p>

<% end %>

<% if user_signed_in? %>
	<h4>Add comment</h4>

	<p>
		<%= form_for([@article, @article.comments.build]) do |f| %>

			<p>
				<%= f.text_area :body, class: "form-control", rows: "4", style: "width: 300px" %>
			</p>

			<p>
				<%= f.submit"Add", class: "btn btn-success" %>
			</p>
		<% end %>
	</p>

<% else %>
	<i>Please <%= link_to "sign in", new_user_session_path %> or <%= link_to "register", new_user_registration_path %> to leave comments.</i>
<% end %>
<hr/>

app/views/users/show.html.erb
<!--p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %-->



<h3><%= @user.name %></h3>
<p>
	<%= @user.email %>
	<br />
	<br />
	<i>Create <%= @user.author %> at <%= @user.created_at %></i>
	<hr/>
</p>

<!--h4>Comments</h4>

<% @article.comments.each do |comment| %>

	<p>
		<%= comment.body %>
		<br />
		<br />
		<i>Said <%= comment.author %> at <%= comment.created_at %></i>
		<hr/>
	</p>

<% end %-->

<% if admin_signed_in? %>
	<h4>Add comment</h4>

	<p>
		<!--%= form_for([@user, @user.mments.build]) do |f| %-->
    <%= form_for([@user]) do |f| %>

			<p>
				<%= f.text_area :body, class: "form-control", rows: "4", style: "width: 300px" %>
			</p>

			<p>
				<%= f.submit"Add", class: "btn btn-success" %>
			</p>
		<% end %>
	</p-->

<% else %>
	<i>Please <%= link_to "sign in", new_admin_session_path %> or <%= link_to "register", new_admin_registration_path %> to leave comments.</i>
<% end %>
<hr/>